debug: true
server:
  port:
    error:
      include-message: always
spring:
  sql:

  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name:
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/gpvhlmff
    username: gpvhlmff
    password: Xp57UHfRz3Nd9MCAt7LZBHnAolMXTPut

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true
        ddl-auto: update
    generate-ddl: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR